---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    slack-webhook-url: AgBCEiVZ27QtVCR0DK+ndtiy6kDXETF/eLPHW2oqAY5u4bA3b00bWTUeuiFfdDBhK6d50lXTa/nkLPDlUM+NTm8ZKk+EKmuSVEisz50NVqV6RW/rnLkg6UMLKnZA4N+PZi3wsmCRK0hQgXlGVgTNXSiXJwMpIe4ew/wnvYmmNCzMazpoH+E5mpaM9o/ic5ggonHDTWE1fXaV96KGmgizEnshbO5JRrbyBRiaOJ6dTOKG0gb3ylNuUi89jyf8E7v9c2x6sfRTlREM5JylIwCNHofaRXw/00wNKeVs31dg+CxRiQAEY9OTyTWDug49L7nCVvl2q4pY/r9uwDVHlGP+BzCdfNQPfK/DhO+plSkOvvTiCPVLjE39o83iBiNpPfEH2G+02ZWHTN4Kg/bEPHDN5GZ3yJgIJ1QilJksqbKM6VaoNrbidW9vzK3zEdETMFOF+hWuWWurAAWo1vOf0KyhMFO3JsA+ZRZ1xJwghPGFqFWyPkNOgwzrwP5xfyOP4sgQRwkEP9bQkM9UNLWf0hl30NbSgZ1BDqM/vqMNdaBmppol7yNqwa45GXo+OXEURyB0YosNML7V/uR/EnqNCB+sd+7JELkEKdUl1XF+Lh+oE93qPNXi8mo6PNS0WlswTeC0Xr2tkN/eVkUVHMlEHQUb/8Yo6FArQeA7a64LFZK8DO4gWv5q+yUVpb7NSCsHdvFvDVoR2Qs6AmUMMKKzBscvStGC6hFy/fMqzAAuad2rdA+ueOJ7bNOYyt+PkhsPgIIXvobFcU446nEL2DbkdqdOS+D96GhgDSljAtKc1R4nlgiVBRU=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack
      namespace: monitoring
    type: Opaque
